"use client";
import {useState} from 'react';
import {ShoppingCart,Wallet,Clock,ShieldCheck,ArrowRight,TriangleAlert,Package,FileText} from 'lucide-react';
import {ResponsiveContainer,AreaChart,Area,XAxis,YAxis,CartesianGrid,Tooltip} from 'recharts';
import {money} from '@/app/catalog';
import type {ManagedProduct} from '@/lib/store-data';
import type {Order} from './panel';
const periods=['Today','Yesterday','7 days','30 days','This year','All'];
const day=86400000;
export default function Overview({orders,products,canOrders,navigate,edit,table}:{orders:Order[];products:ManagedProduct[];canOrders:boolean;navigate:(s:string,status?:string)=>void;edit:(p:ManagedProduct)=>void;table:(rows:Order[])=>React.ReactNode}){
 const [period,setPeriod]=useState('30 days');
 const now=Date.now(),today=Math.floor((now+5*3600000)/day)*day-5*3600000;
 const year=Number(new Date(now+5*3600000).getUTCFullYear());
 const start=period==='Today'?today:period==='Yesterday'?today-day:period==='7 days'?today-6*day:period==='30 days'?today-29*day:period==='This year'?Date.UTC(year,0,1)-5*3600000:Math.min(today-29*day,...orders.map(o=>Date.parse(o.created_at)));
 const end=period==='Yesterday'?today:now+1;
 const length=end-start;
 const current=orders.filter(o=>Date.parse(o.created_at)>=start&&Date.parse(o.created_at)<end);
 const previous=orders.filter(o=>Date.parse(o.created_at)>=start-length&&Date.parse(o.created_at)<start);
 const value=(rows:Order[])=>rows.filter(o=>o.status!=='Cancelled').reduce((s,o)=>s+o.total,0);
 const revenue=value(current),old=value(previous),change=old?((revenue-old)/old*100):null;
 const pending=current.filter(o=>o.status==='Test order received').length;
 const drafts=products.filter(p=>p.status==='Draft');
 const pipeline=[{label:'NEW',status:'Test order received',note:'Awaiting confirmation',color:'#f5a000'},{label:'PROCESSING',status:'Processing',note:'Preparing order',color:'#3987ff'},{label:'SHIPPED',status:'Dispatched',note:'In transit',color:'#25c7c4'},{label:'DELIVERED',status:'Delivered',note:'Completed',color:'#16bb89'}];
 const buckets=12;
 const chart=Array.from({length:buckets},(_,i)=>{const from=start+length*i/buckets,to=start+length*(i+1)/buckets;return {label:new Date(from).toLocaleString('en-PK',{timeZone:'Asia/Karachi',...(length<=day?{hour:'numeric'}:{day:'numeric',month:'short'})}),current:value(current.filter(o=>Date.parse(o.created_at)>=from&&Date.parse(o.created_at)<to)),previous:value(previous.filter(o=>Date.parse(o.created_at)>=from-length&&Date.parse(o.created_at)<to-length))}});
 const sold=new Map<string,{qty:number;total:number}>();current.filter(o=>o.status!=='Cancelled').forEach(o=>o.items.forEach(i=>{const s=sold.get(i.id)||{qty:0,total:0};s.qty+=i.qty;s.total+=i.qty*(i.unitPrice||0);sold.set(i.id,s)}));
 const top=[...sold.entries()].sort((a,b)=>b[1].total-a[1].total).slice(0,5);
 return <div className="seller-overview"><div className="seller-period"><span>Store performance <small>Pakistan time</small></span><div>{periods.map(p=><button key={p} aria-pressed={p===period} onClick={()=>setPeriod(p)}>{p}</button>)}</div></div>
 {canOrders?<><div className="seller-stats">{[{title:'Orders',value:current.length,note:period,icon:ShoppingCart,color:'blue'},{title:'Order value',value:money(revenue),note:change===null?'No previous-period value':`${change>=0?'+':''}${change.toFixed(1)}% vs previous period`,icon:Wallet,color:'green'},{title:'Pending confirmation',value:pending,note:'Awaiting confirmation',icon:Clock,color:'orange'},{title:'Delivered',value:current.filter(o=>o.status==='Delivered').length,note:'This period',icon:ShieldCheck,color:'purple'}].map(s=><div className={'seller-stat '+s.color} key={s.title}><span className="seller-stat-icon"><s.icon size={19}/></span><p>{s.title}</p><strong>{s.value}</strong><small>{s.note}</small></div>)}</div>
 <div className="seller-columns"><div><section className="admin-card"><div className="admin-card-head"><div><h2>Order pipeline</h2><p>Track every order from confirmation to delivery</p></div><button onClick={()=>navigate('orders')}>View all <ArrowRight size={14}/></button></div><div className="seller-pipeline">{pipeline.map(s=><button key={s.status} style={{borderLeftColor:s.color}} onClick={()=>navigate('orders',s.status)}><small>{s.label}</small><strong>{current.filter(o=>o.status===s.status).length}</strong><span>{s.note}</span><ArrowRight size={12}/></button>)}</div></section>
 <section className="admin-card"><div className="admin-card-head"><div><h2>Sales overview</h2><p>Test order value · excludes cancelled orders</p></div><div className="seller-legend"><span><i/>This period<b>{money(revenue)}</b></span>{period!=='All'&&<span><i/>Previous<b>{money(old)}</b></span>}</div></div><div className="seller-chart"><ResponsiveContainer width="100%" height={270}><AreaChart data={chart} margin={{left:0,right:20,top:20,bottom:0}}><defs><linearGradient id="salesFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#6552f5" stopOpacity={.18}/><stop offset="100%" stopColor="#6552f5" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#eef0f6" strokeDasharray="3 4"/><XAxis dataKey="label" axisLine={false} tickLine={false} minTickGap={40} tick={{fontSize:10,fill:'#8491a8'}}/><YAxis axisLine={false} tickLine={false} tick={{fontSize:10,fill:'#8491a8'}} tickFormatter={v=>v>=1000?(v/1000)+'k':v}/><Tooltip formatter={(v:any,name:any)=>[money(Number(v)),name==='current'?'This period':'Previous period']}/>{period!=='All'&&<Area type="linear" dataKey="previous" stroke="#cbd3e2" fill="transparent" strokeDasharray="5 5"/>}<Area type="linear" dataKey="current" stroke="#6351f2" strokeWidth={2} fill="url(#salesFill)"/></AreaChart></ResponsiveContainer></div>{!current.length&&<p className="seller-chart-note">No orders in this period. Your sales chart will update when orders arrive.</p>}</section>
 <section className="admin-card"><div className="admin-card-head"><h2>Recent orders</h2><button onClick={()=>navigate('orders')}>View all <ArrowRight size={14}/></button></div>{table(current.slice(0,6))}</section></div>
 <aside><section className="admin-card"><div className="admin-card-head"><h2>What needs your attention</h2><span className="seller-count">{(pending?1:0)+(drafts.length?1:0)} items</span></div><div className="seller-attention"><div><span className="attention-icon orange"><TriangleAlert size={18}/></span><div><b>{pending} orders waiting on you</b><p>Review and confirm new orders</p></div><button onClick={()=>navigate('orders','Test order received')}>Review</button></div><div><span className="attention-icon purple"><FileText size={18}/></span><div><b>{drafts.length} draft products</b><p>Complete your collection</p></div><button onClick={()=>navigate('products','Draft')}>View</button></div><div><span className="attention-icon green"><Package size={18}/></span><div><b>{current.filter(o=>o.status==='Processing').length} orders being prepared</b><p>Update when ready to ship</p></div><button onClick={()=>navigate('orders','Processing')}>Manage</button></div></div></section>
 <section className="admin-card"><div className="admin-card-head"><h2>Top products</h2><button onClick={()=>navigate('products')}>All <ArrowRight size={14}/></button></div>{top.length?<div className="seller-top-products">{top.map(([id,s])=>{const p=products.find(p=>p.id===id);return <button key={id} onClick={()=>p?edit(p):navigate('orders')}><img src={p?(p.image.startsWith('https://')?p.image:'/images/'+p.image+'.jpg'):'/images/bag.jpg'} alt=""/><div><b>{p?.name||id}</b><small>{s.qty} units ordered</small></div><strong>{money(s.total)}</strong></button>})}</div>:<div className="seller-no-sales"><Package size={26}/><b>Your bestsellers will appear here</b><p>Ranked by product value in the selected period.</p></div>}</section><div className="seller-test-note"><ShieldCheck size={18}/><p>Preview store: orders are tests. No payments are collected or shipments booked. Reports use the latest 1,000 orders.</p></div></aside></div></>:<div className="admin-card admin-empty"><ShieldCheck/><h3>Your content workspace</h3><p>Your role can manage products. Sales reports require order management access.</p><button onClick={()=>navigate('products')}>Manage products</button></div>}
 </div>
}
