"use client";
import {useEffect,useState} from 'react';
import {ArrowRight,ArrowLeft,LockKeyhole,ShieldCheck,Package,ChartNoAxesCombined,Users,LoaderCircle,Eye,EyeOff} from 'lucide-react';
export default function Login({verifiedEmail,signIn,next,initialMode}:{verifiedEmail:string|null;signIn:string;next:string;initialMode:string}){
 const [mode,setMode]=useState(initialMode),[email,setEmail]=useState(verifiedEmail||''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[currentPassword,setCurrentPassword]=useState(''),[code,setCode]=useState(''),[show,setShow]=useState(false),[token,setToken]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{const reset=new URLSearchParams(location.hash.slice(1)).get('reset');if(reset){setMode('reset');setToken(reset);history.replaceState(null,'',location.pathname+location.search)}},[]);
 function switchMode(value:string){setMode(value);setError('');setMessage('');setPassword('');setConfirm('');setCurrentPassword('');setCode('');setShow(false)}
 const creating=['setup','reset','change'].includes(mode);
 async function submit(e:React.FormEvent){e.preventDefault();setError('');setMessage('');if(creating&&password!==confirm){setError('Your passwords do not match.');return}setBusy(true);try{
  const payload={action:mode==='login'?'password-login':mode,email,password,currentPassword,code,token,next};
  const r=await fetch('/api/access/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d:any=await r.json();if(!r.ok)throw Error(d.error||'Unable to complete this request.');
  if(mode==='login'){location.assign(d.next==='/admin/team'?'/admin/team':'/admin');return}
  if(mode!=='forgot'){switchMode('login');setToken('')};setMessage(d.message);
 }catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <main className="admin-login"><aside className="login-story"><a href="/" className="login-brand">zeliy<span>.</span><small>PAKISTAN</small></a><div className="login-story-body"><span className="login-eyebrow">YOUR STORE. YOUR WORKSPACE.</span><h1>Good things<br/>start here<span>.</span></h1><p>A clear view of your business.<br/>Everything you need to keep it moving.</p><div className="login-feature"><Package size={20}/><div><b>Orders & products</b><small>Manage your store in one place</small></div></div><div className="login-feature"><ChartNoAxesCombined size={20}/><div><b>Every detail, at a glance</b><small>Follow your store’s performance</small></div></div><div className="login-feature"><Users size={20}/><div><b>The right access for your team</b><small>Work together with role-based permissions</small></div></div></div><div className="login-story-foot"><ShieldCheck size={16}/>Private seller workspace · Pakistan</div></aside><section className="login-form-side"><a href="/" className="login-back"><ArrowLeft size={15}/>Back to store</a><div className="login-form"><span className="login-lock"><LockKeyhole size={25}/></span><span className="login-eyebrow">ZELIY ADMIN</span><h2>{mode==='login'?'Welcome back':mode==='setup'?'Create your password':mode==='forgot'?'Forgot password?':mode==='change'?'Change password':'Reset password'}</h2><p>{mode==='login'?'Sign in with your admin email and password.':mode==='setup'?'Set a separate password for your verified staff account.':mode==='forgot'?'We’ll email you a secure recovery link.':'Choose a new password. All existing app sessions will be signed out.'}</p>
 {mode==='setup'&&!verifiedEmail?<a className="login-submit" href={signIn} target="_top">Verify your account to set up<ArrowRight size={18}/></a>:<form className="password-form" onSubmit={submit}>
 {['login','setup','forgot'].includes(mode)&&<label>Email address<input type="email" required autoComplete="username" maxLength={254} value={mode==='setup'?verifiedEmail||'':email} readOnly={mode==='setup'} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label>}
 {mode==='change'&&<label>Current password<input type="password" autoComplete="current-password" required maxLength={128} value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/></label>}
 {mode!=='forgot'&&<><label>{creating?'New password':'Password'}<div className="password-input"><input type={show?'text':'password'} autoComplete={creating?'new-password':'current-password'} required minLength={creating?15:1} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" aria-label={show?'Hide password':'Show password'} aria-pressed={show} onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div>{creating&&<small>Use 15–128 characters. A unique passphrase works well.</small>}</label>{creating&&<label>Confirm new password<input type={show?'text':'password'} autoComplete="new-password" required minLength={15} maxLength={128} value={confirm} onChange={e=>setConfirm(e.target.value)}/></label>}<label>Authenticator code <span className="password-optional">if enabled</span><input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}|" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} placeholder="6-digit code"/></label></>}
 {mode==='login'&&<button type="button" className="password-forgot" onClick={()=>switchMode('forgot')}>Forgot password?</button>}
 <button className="login-submit" disabled={busy}>{busy?<><LoaderCircle className="login-spin" size={18}/>Please wait…</>:<>{mode==='login'?'Log in to admin':mode==='setup'?'Create password':mode==='forgot'?'Send recovery link':'Save new password'}<ArrowRight size={18}/></>}</button></form>}
 {error&&<div className="login-error" role="alert"><p>{error}</p></div>}{message&&<div className="password-success" role="status">{message}</div>}
 {mode==='login'?<button className="login-switch" disabled={busy} onClick={()=>switchMode('setup')}>First time? Create your admin password</button>:<button className="login-switch" disabled={busy} onClick={()=>switchMode('login')}>Back to login</button>}
 {mode==='setup'&&<div className="login-help"><b>One-time account verification</b><p>{verifiedEmail?'Your first password is attached to '+verifiedEmail+'. This does not create a new account or change its role.':'Use the verified identity associated with your staff invitation.'} Already have a password? Use recovery instead.</p><a href="/account">View or activate your account</a></div>}
 <div className="login-security"><ShieldCheck size={17}/><p>Only authorized staff can sign in. This private Site also requires permission to open it.</p></div><div className="login-help"><b>Need access?</b><p>Ask your store owner for an invitation. Accept it before creating your first password.</p></div></div><footer>Zeliy Pakistan <span>Secure admin access</span></footer></section></main>
}
