import {z} from 'zod';
import {actor,body,reply,fail,sql,actorGuard,audit,rate,AccessError,now} from '@/lib/access/server';
import {database} from '@/lib/store-data';
import {subcategories,colors,packOptions} from '@/lib/listing-options';
import {ORIGIN} from '@/lib/access/policy';
const information=z.object({category:z.string(),subcategory:z.string(),sku:z.string().trim().min(2).max(60).regex(/^[a-zA-Z0-9 _-]+$/),catalogOwner:z.literal('Zeliy Pakistan'),variants:z.array(z.object({color:z.string().refine(c=>colors.includes(c)),option:z.string().refine(v=>packOptions.includes(v)),image:z.string().refine(v=>v.startsWith(ORIGIN+'/api/media/')&&/^[a-f0-9-]{36}$/.test(v.split('/').pop()||''))})).min(1).max(8)}).refine(d=>subcategories[d.category]?.includes(d.subcategory),{message:'Choose a valid category and subcategory.'}).refine(d=>new Set(d.variants.map(v=>v.color+'|'+v.option)).size===d.variants.length,{message:'Each color and option combination must be unique.'});
export async function GET(req:Request){try{await actor('content.edit');const id=new URL(req.url).searchParams.get('id');if(!id){const rows=await sql("SELECT id,data,created_at FROM listing_drafts WHERE state='draft' ORDER BY created_at DESC LIMIT 20").all<any>();return reply({rows:rows.results.map(r=>({id:r.id,sku:JSON.parse(r.data).sku,createdAt:r.created_at}))});}const row=await sql('SELECT * FROM listing_drafts WHERE id=?',id||'').first<any>();if(!row)throw new AccessError(404,'Draft not found.');return reply({...row,data:JSON.parse(row.data)});}catch(e){return fail(e)}}
export async function POST(req:Request){try{const d=await body(req),u=await actor('content.edit');await rate(u.id,'listing-save',40);
 if(d.action==='draft'){const data=information.parse(d.data),id=crypto.randomUUID();await database().batch([...actorGuard(u),sql('INSERT INTO listing_drafts (id,data,state,created_by,created_at) VALUES (?,?,\'draft\',?,?)',id,JSON.stringify(data),u.id,now()),await audit(u,'content.listing_draft',id,'Saved product information and images')]);return reply({id},201);}
 const input=z.object({action:z.literal('finish'),id:z.string().uuid(),name:z.string().trim().min(3).max(75),description:z.string().trim().min(10).max(3000),features:z.array(z.string().trim().min(1).max(180)).max(8),price:z.number().int().min(1).max(10000000),old:z.number().int().min(1).max(10000000),status:z.enum(['Draft','Active'])}).refine(v=>v.old>=v.price,{message:'Compare-at price cannot be below the selling price.'}).parse(d);
 const row=await sql('SELECT * FROM listing_drafts WHERE id=?',input.id).first<any>();if(!row)throw new AccessError(404,'Draft not found.');const data=information.parse(JSON.parse(row.data));const ids=data.variants.map((v,i)=>'listing-'+input.id+'-'+i);if(row.state==='complete')return reply({ok:true,ids});
 const guard=crypto.randomUUID(),statements=[...actorGuard(u),sql("INSERT INTO access_guard (id,ok) SELECT ?,CASE WHEN EXISTS(SELECT 1 FROM listing_drafts WHERE id=? AND state='draft') THEN 1 ELSE 0 END",guard,input.id),sql('DELETE FROM access_guard WHERE id=?',guard)];
 data.variants.forEach((v,i)=>{const name=input.name+(v.color==='Not applicable'?'':' · '+v.color)+(v.option==='Standard'?'':' · '+v.option);const product={id:ids[i],name,category:data.category,subcategory:data.subcategory,sku:data.sku+'-'+String(i+1).padStart(2,'0'),catalogOwner:data.catalogOwner,listingGroup:input.id,...v,price:input.price,old:input.old,status:input.status,tag:'New arrival',description:input.description,features:input.features};statements.push(sql('INSERT INTO catalog_records (id,data,status) VALUES (?,?,?)',product.id,JSON.stringify(product),input.status));});
 statements.push(sql("UPDATE listing_drafts SET state='complete' WHERE id=?",input.id),await audit(u,'content.listing_created',input.id,'Created product listings',{ids,status:input.status}));await database().batch(statements);return reply({ok:true,ids},201);
 }catch(e){if(e instanceof z.ZodError)return reply({error:e.issues[0]?.message||'Check the product information.'},400);return fail(e)}}
