export const randomToken=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),x=>x.toString(16).padStart(2,'0')).join('');
export async function digest(s:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))),x=>x.toString(16).padStart(2,'0')).join('')}
export function base32(bytes:Uint8Array){const chars='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits=0,value=0,out='';for(const b of bytes){value=(value<<8)|b;bits+=8;while(bits>=5){out+=chars[(value>>>(bits-5))&31];bits-=5}}if(bits)out+=chars[(value<<(5-bits))&31];return out}
export function unbase32(s:string){let bits=0,v=0;const bytes=[];for(const c of s.replace(/=+$/,'')){const n='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'.indexOf(c);if(n<0)throw Error('Invalid secret');v=(v<<5)|n;bits+=5;if(bits>=8){bytes.push((v>>>(bits-8))&255);bits-=8}}return new Uint8Array(bytes)}
export async function otp(secret:string,counter:number,digits=6){const b=new Uint8Array(8);new DataView(b.buffer).setBigUint64(0,BigInt(counter));const key=await crypto.subtle.importKey('raw',unbase32(secret),{name:'HMAC',hash:'SHA-1'},false,['sign']);const h=new Uint8Array(await crypto.subtle.sign('HMAC',key,b));const offset=h[h.length-1]&15;const value=((h[offset]&127)<<24)|(h[offset+1]<<16)|(h[offset+2]<<8)|h[offset+3];return String(value%10**digits).padStart(digits,'0')}
export async function matchCounter(secret:string,code:string,now=Date.now()){if(!/^\d{6}$/.test(code))return -1;const c=Math.floor(now/30000);for(const n of [c,c-1,c+1]){const actual=await otp(secret,n);let diff=0;for(let i=0;i<6;i++)diff|=actual.charCodeAt(i)^code.charCodeAt(i);if(!diff)return n}return -1}
async function key(hex:string){if(!/^[a-f0-9]{64}$/.test(hex||''))throw Error('MFA encryption is not configured');return crypto.subtle.importKey('raw',Uint8Array.from(hex.match(/../g)!.map(x=>parseInt(x,16))),'AES-GCM',false,['encrypt','decrypt'])}
export async function seal(secret:string,hex:string,userId:string){const iv=crypto.getRandomValues(new Uint8Array(12));const data=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode(userId)},await key(hex),new TextEncoder().encode(secret));return btoa(String.fromCharCode(...iv,...new Uint8Array(data)))}
export async function unseal(encrypted:string,hex:string,userId:string){const b=Uint8Array.from(atob(encrypted),c=>c.charCodeAt(0));return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:b.slice(0,12),additionalData:new TextEncoder().encode(userId)},await key(hex),b.slice(12)))}
