import {headers} from 'next/headers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {database} from '@/lib/store-data';
import {OWNER_EMAIL,ROLES,User,has,ORIGIN} from './policy';
import {digest,randomToken} from './crypto';
export class AccessError extends Error{constructor(public status:number,message:string){super(message)}}
export const sql=(q:string,...v:any[])=>database().prepare(q).bind(...v);
export const now=()=>Date.now();
export async function who(){const identity=await getChatGPTUser();const h=await headers();if(!identity||!h.get('oai-authenticated-user-id'))throw new AccessError(401,'Sign in with ChatGPT to continue.');return {...identity,id:h.get('oai-authenticated-user-id')!,email:identity.email.toLowerCase()};}
export async function bootstrap(){const identity=await who();if(identity.email===OWNER_EMAIL){await database().batch([...Object.entries(ROLES).map(([id,r])=>sql('INSERT INTO access_roles (id,name,rank,permissions) VALUES (?,?,?,?) ON CONFLICT(id) DO NOTHING',id,r.name,r.rank,JSON.stringify(r.permissions))),sql('INSERT INTO access_users (id,auth_id,email,name,role,status,created_at) VALUES (?,?,?,?,?,?,?) ON CONFLICT(email) DO NOTHING','owner',identity.id,identity.email,identity.displayName,'super_admin','active',now())]);}return identity}
export async function userRecord(preferPassword=true):Promise<{identity:Awaited<ReturnType<typeof who>>;user:User|null}>{if(preferPassword){const p=await passwordUser();if(p)return {identity:{id:p.auth_id||p.id,email:p.email,displayName:p.name,fullName:p.name},user:p};}const i=await bootstrap();const u=await sql('SELECT * FROM access_users WHERE email=?',i.email).first<User>();if(u?.auth_id&&u.auth_id!==i.id)throw new AccessError(403,'Account identity does not match. Contact the store owner.');return {identity:i,user:u};}
export async function blocked(id:string,kind='ban'){return !!await sql('SELECT id FROM access_bans WHERE user_id=? AND kind=? AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at>?) LIMIT 1',id,kind,now()).first()}
export async function passwordUser():Promise<User|null>{const h=await headers();const token=h.get('cookie')?.match(/(?:^|;\s*)__Host-zeliy_session=([a-f0-9]{64})(?:;|$)/)?.[1];if(!token)return null;const row=await sql("SELECT u.* FROM access_sessions s JOIN access_users u ON u.id=s.user_id WHERE s.token_hash=? AND s.source='password' AND s.version=u.session_version AND s.expires_at>?",await digest(token),now()).first<User>();return row;}
export async function actor(permission?:string,session=true):Promise<User>{
 let u=session?await passwordUser():null;
 if(!u){const record=await userRecord(false);u=record.user;if(!u||u.status!=='active')throw new AccessError(403,u?.status==='removed'?'Your account has been removed.':'Activate your account from My account first.');
 if(await blocked(u.id))throw new AccessError(403,'Your account is banned.');if(session){const h=await headers();const token=h.get('cookie')?.match(/(?:^|;\s*)__Host-zeliy_session=([a-f0-9]{64})(?:;|$)/)?.[1];const valid=token?await sql("SELECT id FROM access_sessions WHERE token_hash=? AND user_id=? AND version=? AND source='platform' AND expires_at>?",await digest(token),u.id,u.session_version,now()).first():null;if(!valid)throw new AccessError(401,'Your app session expired or was revoked. Sign in again.');if(has(u,'users.read')&&await sql('SELECT user_id FROM access_passwords WHERE user_id=?',u.id).first())throw new AccessError(401,'Use your email and password to access admin.');}}
 if(u.status!=='active'||await blocked(u.id))throw new AccessError(403,'Your account is banned or inactive.');
 if(permission==='content.edit'&&await blocked(u.id,'mute'))throw new AccessError(403,'Your account is restricted from content management.');
 if(permission&&!has(u,permission))throw new AccessError(403,'Your role does not permit this action.');return u;
}
export function origin(req:Request){if(req.headers.get('origin')!==ORIGIN)throw new AccessError(403,'Invalid request origin.');}
export async function body(req:Request){origin(req);if(Number(req.headers.get('content-length')||0)>50000)throw new AccessError(413,'Request is too large.');const reader=req.body?.getReader();let raw='',length=0;const decoder=new TextDecoder();if(reader){while(true){const {value,done}=await reader.read();if(done)break;length+=value.byteLength;if(length>50000){await reader.cancel();throw new AccessError(413,'Request is too large.');}raw+=decoder.decode(value,{stream:true});}raw+=decoder.decode();}try{return JSON.parse(raw)}catch{throw new AccessError(400,'Invalid JSON request')}}
export function fail(e:unknown){if(e instanceof AccessError)return Response.json({error:e.message},{status:e.status,headers:{'Cache-Control':'no-store'}});if((e as any)?.name==='ZodError')return Response.json({error:'Check your form values.',details:(e as any).issues},{status:400});console.error('Access operation failed',e instanceof Error?e.message:'unknown');return Response.json({error:'Unable to complete this request. Refresh and try again.'},{status:503})}
export const reply=(d:unknown,status=200,headers:Record<string,string>={})=>Response.json(d,{status,headers:{'Cache-Control':'no-store',...headers}});
export async function rate(u:string,action:string,limit=30,ms=3600000){const t=now(),bucket=Math.floor(t/ms),key=u+':'+action+':'+bucket;const r=await sql('INSERT INTO access_rate (key,count,expires_at) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count',key,t+ms*2).first<{count:number}>();await sql('DELETE FROM access_rate WHERE key IN (SELECT key FROM access_rate WHERE expires_at<? LIMIT 100)',t).run();if(r!.count>limit)throw new AccessError(429,'Rate limit reached. Please try again later.');}
export async function audit(u:User,action:string,target:string,reason:string,metadata:unknown={}){const h=await headers();return sql('INSERT INTO access_audit (id,actor_id,target_id,action,reason,metadata,ip,device,created_at) VALUES (?,?,?,?,?,?,?,?,?)',crypto.randomUUID(),u.id,target,action,reason,JSON.stringify(metadata),h.get('cf-connecting-ip')?.slice(0,64)||null,h.get('user-agent')?.slice(0,300)||null,now())}
export const notice=(id:string,message:string)=>sql('INSERT INTO access_notices (id,user_id,message,created_at) VALUES (?,?,?,?)',crypto.randomUUID(),id,message,now());
// Guard rows have a CHECK constraint. A failed guard aborts the whole D1 batch.
export function actorGuard(u:User){const key=crypto.randomUUID();return [sql(`INSERT INTO access_guard (id,ok) SELECT ?, CASE WHEN EXISTS(SELECT 1 FROM access_users WHERE id=? AND version=? AND status='active') AND NOT EXISTS(SELECT 1 FROM access_bans WHERE user_id=? AND kind='ban' AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at>?)) THEN 1 ELSE 0 END`,key,u.id,u.version,u.id,now()),sql('DELETE FROM access_guard WHERE id=?',key)]}
export function targetGuard(u:User){const key=crypto.randomUUID();return [sql('INSERT INTO access_guard (id,ok) SELECT ?,CASE WHEN EXISTS(SELECT 1 FROM access_users WHERE id=? AND version=?) THEN 1 ELSE 0 END',key,u.id,u.version),sql('DELETE FROM access_guard WHERE id=?',key)]}
export async function issueSession(u:User,adminLogin=false,source='platform',extra:ReturnType<typeof sql>[]=[]){const token=randomToken();await database().batch([...actorGuard(u),...extra,sql('DELETE FROM access_sessions WHERE id IN (SELECT id FROM access_sessions WHERE expires_at<? LIMIT 1000)',now()),sql('INSERT INTO access_sessions (id,token_hash,user_id,version,source,expires_at) VALUES (?,?,?,?,?,?)',crypto.randomUUID(),await digest(token),u.id,u.session_version,source,now()+8*3600000),sql('UPDATE access_users SET last_seen=? WHERE id=?',now(),u.id),...(adminLogin?[await audit(u,'session.admin_login',u.id,'Signed in to the admin workspace',{method:source})]:[])]);return '__Host-zeliy_session='+token+'; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=28800';}
