import { actor,actorGuard,audit,fail,origin,sql } from '@/lib/access/server';
import {has} from '@/lib/access/policy';
import { database,catalog,settings } from '@/lib/store-data';
import { z } from 'zod';
import { categories } from '@/app/catalog';
const reply=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
const productSchema=z.object({id:z.string().regex(/^[a-z0-9-]{1,100}$/),name:z.string().trim().min(3).max(120),category:z.string().refine(c=>categories.slice(1).includes(c)),price:z.number().int().min(1).max(10000000),old:z.number().int().min(1).max(10000000),image:z.string().max(1500).refine(s=>['headphones','bag','shoes','beauty','watch','kitchen'].includes(s)||/^https:\/\/[^\s]+$/.test(s)),tag:z.string().max(60),description:z.string().trim().min(10).max(3000),features:z.array(z.string().trim().min(1).max(180)).max(8),status:z.enum(['Active','Draft'])}).refine(p=>p.old>=p.price,{message:'Compare-at price must be at least the selling price.'});
const settingSchema=z.object({deliveryCharge:z.number().int().min(0).max(100000),freeThreshold:z.number().int().min(0).max(10000000),supportEmail:z.union([z.literal(''),z.string().email().max(100)]),whatsapp:z.string().regex(/^(923\d{9})?$/)});
export async function GET(){try{const u=await actor('content.edit');const [products,config,rows]=await Promise.all([catalog(true),settings(),has(u,'orders.manage')?database().prepare('SELECT id, details, items, total, status, created_at FROM orders ORDER BY created_at DESC LIMIT 1000').all():Promise.resolve({results:[]})]);return reply({products,settings:config,name:u.name,role:u.role,permissions:(await import('@/lib/access/policy')).ROLES[u.role].permissions,orders:rows.results.map((o:any)=>({...o,details:JSON.parse(o.details),items:JSON.parse(o.items)}))});}catch(e){return fail(e)}}
export async function POST(req:Request){try{origin(req);const u=await actor('content.edit');const raw=await req.text();if(raw.length>20000)return reply({error:'Request too large.'},413);const data=JSON.parse(raw);if(data.action==='product'){const p=productSchema.parse(data.product);const current=await catalog(true);if(current.some(x=>x.id===p.id&&x.category!==p.category))return reply({error:'Category cannot be changed after creation because it determines product sizes.'},400);await database().batch([...actorGuard(u),sql('INSERT INTO catalog_records (id,data,status) VALUES (?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,status=excluded.status',p.id,JSON.stringify({...current.find(x=>x.id===p.id),...p}),p.status),await audit(u,'content.product_saved',p.id,'Product saved',{status:p.status,price:p.price})]);return reply({ok:true});}if(data.action==='settings'){await actor('settings.edit');const s=settingSchema.parse(data.settings);await database().batch([...actorGuard(u),sql('INSERT INTO store_settings (id,data) VALUES (?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data','store',JSON.stringify(s)),await audit(u,'settings.updated','store','Store settings updated')]);return reply({ok:true});}if(data.action==='order'){await actor('orders.manage');const p=z.object({id:z.string().max(100),status:z.enum(['Test order received','Processing','Dispatched','Delivered','Cancelled'])}).parse(data);const existing=await sql('SELECT id FROM orders WHERE id=?',p.id).first();if(!existing)return reply({error:'Order not found.'},404);await database().batch([...actorGuard(u),sql('UPDATE orders SET status=? WHERE id=?',p.status,p.id),await audit(u,'order.status_changed',p.id,'Order status updated',{status:p.status})]);return reply({ok:true});}return reply({error:'Unknown action.'},400);}catch(e){if(e instanceof z.ZodError)return reply({error:e.issues[0]?.message||'Check the entered values.'},400);return fail(e)}}
