import {actor,blocked,AccessError,fail,actorGuard,sql,origin} from '@/lib/access/server';
import {database} from '@/lib/store-data';
import { getDb } from '@/db';
import { orders } from '@/db/schema';
import { and, eq } from 'drizzle-orm';
import { catalog, settings, deliveryFor } from '@/lib/store-data';
import { z } from 'zod';
const schema=z.object({name:z.string().trim().min(2).max(80),phone:z.string().regex(/^(03\d{9}|\+923\d{9})$/),email:z.union([z.literal(''),z.string().email().max(100)]).optional(),address:z.string().trim().min(8).max(250),city:z.string().trim().min(2).max(60),postal:z.string().regex(/^(\d{5})?$/).optional(),note:z.string().max(300).optional(),items:z.array(z.object({id:z.string(),qty:z.number().int().min(1).max(10),size:z.string().max(20)})).min(1).max(30)});
export async function POST(req:Request){try{origin(req);const user=await actor();if(await blocked(user.id,'mute'))throw new AccessError(403,'Your account is restricted from placing orders.');if(Number(req.headers.get('content-length')||0)>15000)return Response.json({error:'Order is too large.'},{status:413});const parsed=schema.safeParse(await req.json());if(!parsed.success)return Response.json({error:'Please check your name, Pakistani mobile number and delivery address.'},{status:400});const {items,...details}=parsed.data;const [products,config]=await Promise.all([catalog(),settings()]);let subtotal=0;const seen=new Set();for(const i of items){const p=products.find(p=>p.id===i.id);if(!p||seen.has(i.id+':'+i.size)||!(p.category==='Fashion'?['38','39','40','41','42','43','44'].includes(i.size):i.size==='Standard'))return Response.json({error:'Please review the items in your bag.'},{status:400});seen.add(i.id+':'+i.size);subtotal+=p.price*i.qty;}const id='ZPK-'+crypto.randomUUID().slice(0,8).toUpperCase();const token=crypto.randomUUID();const total=subtotal+deliveryFor(subtotal,config);await database().batch([...actorGuard(user),sql('INSERT INTO orders (id,token,details,items,total,status,created_at) VALUES (?,?,?,?,?,?,?)',id,token,JSON.stringify(details),JSON.stringify(items.map(i=>({...i,name:products.find(p=>p.id===i.id)!.name,unitPrice:products.find(p=>p.id===i.id)!.price}))),total,'Test order received',new Date().toISOString())]);return Response.json({id,token,total,status:'Test order received'},{status:201,headers:{'Cache-Control':'no-store'}})}catch(e){return fail(e)}}
export async function GET(req:Request){try{await actor();const url=new URL(req.url);const id=url.searchParams.get('id')||'';const token=url.searchParams.get('token')||'';if(!id||!token)return Response.json({error:'Enter your order reference and tracking key.'},{status:400});const [order]=await getDb().select({id:orders.id,total:orders.total,status:orders.status,createdAt:orders.createdAt}).from(orders).where(and(eq(orders.id,id),eq(orders.token,token))).limit(1);if(!order)return Response.json({error:'Order not found. Check your reference and tracking key.'},{status:404});return Response.json(order,{headers:{'Cache-Control':'no-store'}})}catch(e){return fail(e)}}
